### ISSUE TITLE
AttributeError: 'list_iterator' object has no attribute 'remove'

### ISSUE THREAD

**Issue by cbelth** [Toyzenk/PNRL#1]
Hello, when I run `python pnrl_r.py`, I get the following error: 
```
Using TensorFlow backend.
Creating neighbor set...
Finish creating neighbor set
Creating negative sampling table...
Finish
Creating Validation edges set...
Creating Validation edges set...
pnrl_r.py:94: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
  model1 = Model(input=[input_source, context_input], output=[nrl_output])
pnrl_r.py:103: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="linear", name="BiW", kernel_regularizer=<keras.reg..., use_bias=False)`
  XW =  Dense(dim_embedddings, activation='linear', W_regularizer=l2(0.01), bias=False,name='BiW')(X_S)
pnrl_r.py:107: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
  model2 = Model(input=[input_source, input_pos, input_neg], output=[lp_output])
Traceback (most recent call last):
  File "pnrl_r.py", line 261, in <module>
    train(config)
  File "pnrl_r.py", line 219, in train
    ob_edges, hi_edges, ob_ns, hi_ns = hidden_edge_sampling(sample_iter, sample_size, edges, ns_complete)
  File "pnrl_r.py", line 123, in hidden_edge_sampling
    ns[e[0]].remove(e[1])
AttributeError: 'list_iterator' object has no attribute 'remove'
```
Any idea what I can do to resolve this?

**Comment by zhitao-wang** [comment]
Hello Cbelth,

Cause:
It may be caused by the version of NetworkX. I guess you may use a more recent version of NetworkX. The details are as follows:
"ns" is a dictionary storing neighbors of each node, "ns[]" should be a list of a's neighbors (a 'list' object).
In file "util.py", line 74, we use "nx.neighbors(G,node)" (NetworkX function) to get neighrbor list for each node.
In old version of NetworkX, "nx.neighbors(G,node)" will return a 'list' object.
But when I check the docs of new version (2.4), the function will return a 'iterator' object.

Solution:
Transfer 'iterator' object to 'list' object.
Code change: In file "util.py", line 75,
neighbor_set[node] = neighbours  -> neighbor_set[node] = list(neighbours)

`def neighbor_set(G):
    neighbor_set = {}
    non_neighbor_set = {}
    whole_set = set(G.nodes())
    print('Creating neighbor set...')
    for node in G.nodes():
        neighbours = nx.neighbors(G,node)
        neighbor_set[node] = list(neighbours)   #neighbours
        non_neighbor_set[node] = list(whole_set-set(neighbours))
    print('Finish creating neighbor set')
    return neighbor_set, non_neighbor_set`

**Comment by zhitao-wang** [comment]
> Hello, when I run `python pnrl_r.py`, I get the following error:
> 
> ```
> Using TensorFlow backend.
> Creating neighbor set...
> Finish creating neighbor set
> Creating negative sampling table...
> Finish
> Creating Validation edges set...
> Creating Validation edges set...
> pnrl_r.py:94: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
>   model1 = Model(input=[input_source, context_input], output=[nrl_output])
> pnrl_r.py:103: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="linear", name="BiW", kernel_regularizer=<keras.reg..., use_bias=False)`
>   XW =  Dense(dim_embedddings, activation='linear', W_regularizer=l2(0.01), bias=False,name='BiW')(X_S)
> pnrl_r.py:107: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
>   model2 = Model(input=[input_source, input_pos, input_neg], output=[lp_output])
> Traceback (most recent call last):
>   File "pnrl_r.py", line 261, in <module>
>     train(config)
>   File "pnrl_r.py", line 219, in train
>     ob_edges, hi_edges, ob_ns, hi_ns = hidden_edge_sampling(sample_iter, sample_size, edges, ns_complete)
>   File "pnrl_r.py", line 123, in hidden_edge_sampling
>     ns[e[0]].remove(e[1])
> AttributeError: 'list_iterator' object has no attribute 'remove'
> ```
> 
> Any idea what I can do to resolve this?

**Comment by zhitao-wang** [comment]
> Hello, when I run `python pnrl_r.py`, I get the following error:
> 
> ```
> Using TensorFlow backend.
> Creating neighbor set...
> Finish creating neighbor set
> Creating negative sampling table...
> Finish
> Creating Validation edges set...
> Creating Validation edges set...
> pnrl_r.py:94: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
>   model1 = Model(input=[input_source, context_input], output=[nrl_output])
> pnrl_r.py:103: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="linear", name="BiW", kernel_regularizer=<keras.reg..., use_bias=False)`
>   XW =  Dense(dim_embedddings, activation='linear', W_regularizer=l2(0.01), bias=False,name='BiW')(X_S)
> pnrl_r.py:107: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
>   model2 = Model(input=[input_source, input_pos, input_neg], output=[lp_output])
> Traceback (most recent call last):
>   File "pnrl_r.py", line 261, in <module>
>     train(config)
>   File "pnrl_r.py", line 219, in train
>     ob_edges, hi_edges, ob_ns, hi_ns = hidden_edge_sampling(sample_iter, sample_size, edges, ns_complete)
>   File "pnrl_r.py", line 123, in hidden_edge_sampling
>     ns[e[0]].remove(e[1])
> AttributeError: 'list_iterator' object has no attribute 'remove'
> ```
> 
> Any idea what I can do to resolve this?

Hello Cbelth,

**Cause:**
It may be caused by the version of NetworkX. I guess you may use a more recent version of NetworkX. The details are as follows:

- `ns` is a dictionary storing neighbors of each node, `ns[e[0]]` should be a list of `e[0]`'s neighbors ( `'list' object`).

- In file "util.py", line 74, we use `neighbours = nx.neighbors(G,node)` (a function in NetworkX) to get neighrbor list for each node.

- In old version of NetworkX, `nx.neighbors(G,node)` will return a `'list' object`. But when I check the docs of new version (2.4), the function will return a `'iterator' object`.

**Solution:**
Transfer `'iterator' object` to `'list' object`. Code changes are: 
In file "util.py", line 75, `neighbor_set[node] = neighbours`  -> `neighbor_set[node] = list(neighbours)`

**Comment by cbelth** [comment]
Thank you, that resolved it!
